name: Install
description: Installs poetry and the poetry environment as an action

inputs:
  python-version:
    description: Version of python to use
    required: true
    default: 3.10
  poetry-version:
    description: Version of poetry to install
    required: true
    default: 1.6.1

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    -name: Init python and poetry
      uses: ./.github/actions/init-poetry
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}

    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

    - name: Install dependencies
      shell: bash
      run: |
          poetry install -E percep