name: Publish a release to TestPyPI

on:
  push:
    tags:
      - "test-v*.*.*"

jobs:
  # the tests must pass before release is to be made
  # test:
  #   name: Run unit tests on release branch
  #   uses: ./.github/workflows/test_on_branch.yml
  #   with:
  #     branch: release
  #     os: ubuntu-22.04  

  # then we build to prep for release
  build:
    name: Build and publish the package to pypi
    # needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Init poetry and python
        uses: ./.github/actions/init-poetry
        with:
          python-version: "3.10"
          poetry-version: "1.6.1"
      
      - name: Build package
        shell: bash
        run: |
            poetry build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  # now we publish the release
  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs: build
    runs-on: ubuntu-22.04

    environment:
      name: testpypi
      url: https://test.pypi.org/p/avstack-core

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/