name: Run tests on some branch

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      os:
        default: ubuntu-22.04
        type: string

jobs:
  build_and_test:
    name: Run unit tests on ${{ inputs.branch }} branch

    runs-on: ${{ inputs.os }}

    strategy:
      matrix:
        python-version: [ "3.10" ]
        poetry-version: [ "1.6.1" ]
  
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/actions/install
        with: 
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}

      - name: Run unit tests
        uses: ./.github/actions/test
        with:
          test-folder: tests